Feature: Alterar Resolução

  Scenario Outline: Alterar resolução com sucesso
    Given o servidor seleciona a resolução "<resolucao>"
    And o servidor informa os dados da resolução "<sigla>", "<nome>", "<descricao>", "<percentual>", "<data_inicio>", "<modalidades_bolsa>"
    When o servidor altera a resolução
    Then o sistema deve salvar a resolução com status "Em edição"

    Examples:
      | resolucao | sigla | nome | descricao | percentual | data_inicio | modalidades_bolsa |
      | Res1      | ABC   | Nome | Desc      | 10         | 2024-01-01  | Bolsa1            |

  Scenario Outline: Alterar resolução com erro - Campo obrigatório
    Given o servidor seleciona a resolução "<resolucao>"
    And o servidor informa os dados da resolução "<sigla>", "<nome>", "<descricao>", "<percentual>", "<data_inicio>", "<modalidades_bolsa>"
    When o servidor altera a resolução
    Then o sistema deve retornar uma mensagem de erro "<mensagem_erro>"

    Examples:
      | resolucao | sigla | nome | descricao | percentual | data_inicio | modalidades_bolsa | mensagem_erro                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Res1      |       | Nome | Desc      | 10         | 2024-01-01  | Bolsa1            | A sigla da resolução é obrigatória                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | Res1      | ABC   |       | Desc      | 10         | 2024-01-01  | Bolsa1            | O nome da resolução é obrigatório                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Res1      | ABC   | Nome |          | 10         | 2024-01-01  | Bolsa1            | A descrição da resolução é obrigatória                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | Res1      | ABC   | Nome | Desc      |          | 2024-01-01  | Bolsa1            | O percentual da resolução é obrigatório                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Res1      | ABC   | Nome | Desc      | 10         |             | Bolsa1            | A data de início da resolução é obrigatória                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Res1      | ABC   | Nome | Desc      | 10         | 2024-01-01  |                 | A modalidade de bolsa da resolução é obrigatória                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |

  Scenario Outline: Alterar resolução com erro - Validação de dados
    Given o servidor seleciona a resolução "<resolucao>"
    And o servidor informa os dados da resolução "<sigla>", "<nome>", "<descricao>", "<percentual>", "<data_inicio>", "<modalidades_bolsa>"
    When o servidor altera a resolução
    Then o sistema deve retornar uma mensagem de erro "<mensagem_erro>"

    Examples:
      | resolucao | sigla | nome | descricao | percentual | data_inicio | modalidades_bolsa | mensagem_erro                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Res1      | ABC   | Nome | Desc      | -10        | 2024-01-01  | Bolsa1            | O percentual da resolução deve ser um valor positivo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | Res1      | ABC   | Nome | Desc      | 10         | 2023-01-01  | Bolsa1            | A data de início da resolução deve ser uma data válida e maior que a data atual                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

  Scenario Outline: Alterar resolução com erro - Regra de integridade
    Given o servidor seleciona a resolução "<resolucao>"
    And o servidor informa os dados da resolução "<sigla>", "<nome>", "<descricao>", "<percentual>", "<data_inicio>", "<modalidades_bolsa>"
    When o servidor altera a resolução
    Then o sistema deve retornar uma mensagem de erro "<mensagem_erro>"

    Examples:
      | resolucao | sigla | nome | descricao | percentual | data_inicio | modalidades_bolsa | mensagem_erro                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Res1      | ABC   | Nome | Desc      | 10         | 2024-01-01  | Bolsa2            | A modalidade de bolsa informada não está cadastrada no sistema. Por favor, cadastre a modalidade de bolsa antes de alterar a resolução.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |